---
title: "Теория групп и теория чисел"
author: "Юрченков Иван Александрович"
date: "10 02 2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Теория групп

## Группа подстановок. Перестановки. Последовательное выполнение подстановок. Разложение подстановок в циклы. Транспозиция.

## Понятие группы. Числовые группы. Определение групп

## Свойства элементов группы. Различные способы определения группы. Тождества в группе. Коммутативные группы.

## Теоретико-групповые конструкции. Подгруппы группы. Фактор-группа. Прямое произведение групп

## Отображение групп. Изоморфизм групп. Гомоморфное отображение. Операции, осуществляемые гомоморфизмами.

## Полугруппы и автоматы. Полугруппы с единицей. Алгебраическая теория автоматов.

## Представление групп. Кольца и тела. Целые числа и многочлены. Разложение многочленов целых чисел на простые множители.

## Векторные пространства и модули. Свойства векторов и элементов. Пространства, порожденные векторами. Линейная зависимость. Размерность. Изоморфизм. Прямая сумма векторных пространств. Модули коразмерности.

## Однородное линейное отображение. Гомоморфизм векторных пространств. Операции над однородными линейными отображениями. Матрицы. 

## Группы и кольца. Представление групп матрицами. Групповые алгебры. 

## Структуры и операции над множествами. Специальные структуры. Частично упорядоченные множества и структуры. 

## Соотношения между структурами. Подструктура. Гомоморфизм. Прямое произведение.

## Идеал. Примарный идеал. Логические связки. Представление структур.

## Основные направления развития абстрактной алгебры.

# Теория чисел

## История теоремы Ферма. Теорема Жермен. Формула Абеля. Сравнения. Следствия.

## Теорема Ферма для n=4. Доказательство.

## Теорема Ферма для n=3. Доказательство. Лемма Эйлера

## Арифметика кольца $D_3$

## Норма. Целые кольца. Арифметика неприводимых многочленов. Единица кольца $D_3$. Понятие элемента. Разложение на простые множители.

## Кольцо вычетов. Китайская теорема об остатках. Проверка на простоту. Псевдопростые числа. Числа Картмайкла. Построение больших простых чисел. Китайское определение простого числа. Представление составного целого числа в виде разности квадратов. Метод фактор-баз Ферма. Тест Миллера-Рабина. 

## Арифметика в кольцах. Кольцо главных идеалов. Евклидовы кольца. Алгоритм деления в кольце D.

## Неприводимость многочлена деления круга. Автоморфизм поля $K_l$. Существование первообразных корней в поле $K_l$. Кольцо $D_l$. Его единственность. Теорема дивизоров. Свойства дивизоров.

## Теория идеалов. 

## Целые алгебраические числа. Регулярные простые числа. Куммеровы простые числа.


# Литература

## 
