---
title: "Практическое занятие №8. Кольца"
output:
  html_document:
    df_print: paged
---

# **Теорема о гомоморфизме**

## Ядро гомоморфизма

**Определение**. Отображение $\varphi:G \rightarrow G^{'}$, где $G, G^{'}$ - две группы, называется гомоморфизмом, если:

$$
\varphi(a \cdot b) = \varphi(a) \circ \varphi(b)
$$

Ядром $ker(\varphi)$ гомоморфизма $\varphi$ называется множество элементов группы $G$, отображающихся в нейтральный элемент $e_{G^{'}}$ группы $G^{'}$:

$$
Ker(\varphi) = \{g\ | \ g\in G, \varphi(g) = e_{G^{'}}\}.
$$


- Ядро произвольного изоморфизма состоит из нейтрального элемента

- Ядро гомоморфизма является нормальной подгруппой, то есть $Ker(\varphi) \triangleleft G$

**Утверждение**. Пусть задан гомоморфизм $\varphi: G \rightarrow G^{'}$. Ядро гомоморфизма $Ker(\varphi)$ является нормальной подгруппой $G$, то есть $Ker(\varphi) \triangleleft G$.

**Доказательство**.

$\forall x: x\in Ker(\varphi)\ \ \ \ \varphi(x) \circ \varphi(x^{-1}) = \varphi(x) \circ \varphi(x)^{-1} = \varphi(e) = e_{G^{'}}$

$\varphi(x) = e_{G^{'}} \rightarrow  \varphi(x^{-1}) = e_{G^{'}} \rightarrow x^{-1} \in Ker(\varphi)$

$$
\forall y,x: y,x \in Ker(\varphi)\ \ \ \varphi(y\cdot x^{-1}) = \varphi(y) \circ \varphi(x)^{-1} = \varphi(e) \circ \varphi(e) = e_{G^{'}} \rightarrow y\cdot x^{-1} \in Ker(\varphi) 
$$


$$\forall x: x\in Ker(\varphi) \ \ \ \forall g: g\in G \ \ \ \varphi(g \cdot x \cdot g^{-1}) = \varphi(g) \circ \varphi(x) \circ \varphi(g^{-1}) = \varphi(g) \circ e_{G^{'}} \circ \varphi(g^{-1}) = \varphi(e) = e_{G^{'}}$$

**ч.т.д**


## Теорема о гомоморфизме

**Теорема**. Пусть задан гоморфизм $\varphi: G \rightarrow G^{'}$. Тогда гомоморфный образ группы $Im(G) = \varphi(G)$ изоморфен фокторгруппе по ядру гомоморфизма:

$$
Im(G) = g(G) \cong G / Ker(\varphi)
$$

**Идея доказательства:** 

Рассмотрим смежные классы по подгруппе $Ker(\varphi)$

$$
\forall g: g \in G\ \ \ \varphi(g \cdot Ker(\varphi)) =  \varphi(g) \circ \varphi(Ker(\varphi)) = \varphi(g)
$$

То есть каждому смежному классу $g Ker(\varphi)$ по $Ker(\varphi)$ можно поставить во взаимно однозначное соответствие элемент образа $\varphi(g) \in Im(G)$.

# **Кольца**

## Определение

Алгебраическая структура. Множество и алгебраические операции над ними.

**Кольцом** называется множество $M$ с заданными на нём двумя алгебраическими операциями, которые обозначают $+$ и $*$ (сложение и умножение) и тремя аксиомами:

А1: Кольцо является коммутативной группой по сложению

А2: Умножение над множеством элементов кольца ассоциативно: $\forall a, b, c: a, b, c \in M \ \ \ (a \cdot b) \cdot c = a \cdot (b \cdot c)$

А3: Умножение дистрибутивно относительно сложения: 

$$
  \forall a,b, c: a, b, c \in M \\
  (a + b) \cdot c = a\cdot c + b \cdot c \\
  c \cdot (a + b) = c \cdot a + c \cdot b
$$

Дистрибутивность слева и справа записываются по разному из-за того, что в *A2* нет условия на коммутативность операции умножения.

**Коммутативным кольцом** называется кольцо над множеством $M$ с коммутативной операцией умножения.

## Обозначения в кольцах

$$
R = <M, \{+, \cdot\}>
$$

Нейтральный элемент по сложению обозначают 0.

Нейтральный элемент по умножению обозначают 1. Нейтральный элемент по умножению есть не всегда. 

Если у кольца есть нейтральный элемент по умножению, то такое кольцо называется **кольцом с единицей**.


## Примеры колец

- $\mathbb{Z}$  относительно операции сложения и умножения

- $\mathbb{Q}$ относительно операции сложения и умножения

- Остатки от деления на натуральное число $m$ относительно операции сложения и умножения. (*Модулярная арифметика -- кольцо*)

## Свойства колец

*Делителями нуля* называются такие $a$ и $b$, что каждое из них в отдельности не ноль, а произведение -- ноль.

$$
a \ne 0, \ b \ne 0, \ \ \ \ \ a \cdot b = 0
$$

*Целостное кольцо* -- коммутативное кольцо, в котором нет делителей нуля

*Обратимыми* называют такие элементы кольца, для которых существует обратный по умножению

- Делители нуля необратимы

- Декартово произведение колец - кольцо

- Если в кольце $1 = 0$ единичка и ноль совпадают, то других элементов в кольце нет

- $a \cdot 0 = 0$ -- в кольцах неочевидно, необходимо доказывать

- $a (b - c) = ab - ac$

**Утверждение**. $\forall a,b,c \in R \ \ \ \ a (b - c) = ab - ac$

**Доказательство**. Докажем дистрибутивность относительно вычитания.

$$a (b + (-c)) + ac = a(b + (-c) + c) = ab \rightarrow -ac = a (-c)$$

$$
a (b + (-c)) + ac - ac = a(b + (-c)) = ab - ac
$$

**Утверждение**. $\forall a \in R \ \ \ a\cdot 0 = 0$

**Доказательство**: Умножение **слева**

$$
a(b - c) = ab - ac \\
a(b - b) = ab - ab \\
a \cdot 0 = 0
$$


**Утверждение**. Делители нуля необратимы

**Доказательство**:

$$
a,b \ne 0 \ \ \ \ a\cdot b = 0 \\
\exists c \in R \ \ \ \ \ b\cdot c = 1 \\
a\cdot b \cdot c = 0\cdot c = 0 = a \cdot 1 = a
$$
Приходим к противоречию

# **Кольца многочленов**

## Определение

Пусть $R$ -- коммутативное кольцо с единицей

Рассмотрим финитные последовательности в $R$: $a_0, a_1, a_2, \dots, a_n, 0, 0, 0, \dots$. Данной последовательности конечным является число ненулевых элементов. Запишем эту финитную последовательность в виде многочлена:

$$
  f(x) = a_0 + a_1 x + a_2 x^2 + \cdots + a_n x^n, \ \ \ a_n \ne 0 \\
  f(x) = a_0 + a_1 x + a_2 x^2 + \cdots + a_n x^n + 0 x^{n+1} + \cdots
$$

Это просто удобная форма записи такой последовательности.

Данные многочлены и будут элементами множества $M$ нашего *кольца многочленов*. 

## Операции на кольце многочленов

Введем операции сложения и умножения по аналогии с многочленами:

$$
g(x) = b_0 + b_1x + b_2x^2 + \cdots + b_mx^m
$$

$$
f(x) + g(x) = \sum_{k = 0} ^{max(n,m)} (a_k + b_k) x^k
$$


$$
f(x) \cdot g(x) = \sum_{k=0}^{n+m} \left( \sum_{j = 0}^{k} a_j \cdot b_{k - j} \right) x^{k}
$$

Введение многочленов нужно было просто для того, чтобы определить удобный способ обращаться с финитными последовательностями чисел над кольцом $R$

Множество $R[x]$ многочленов с коэффициентами из $R$ называют **кольцом многочленов** над $R$.

## Свойства 

- $R[x]$ является кольцом

- $R[x]$ -- коммутативное кольцо

- $R[x]$ -- кольцо с единицей

- Если $R$ целостное, и $f(x) \ne 0$, $g(x) \ne 0$, то 

$$
deg(fg) = deg(f) + deg(g)
$$

- Если $R$ -- целостное, то и $R[x]$ -- целостное

- Обратимые элементы в кольце многочленов $R[x]$ над целостным кольцом $R$ -- это многочлены степени 0, обратимые в кольце $R$

# **Идеалы**

## Определение

В кольцах вводится структура, аналогичная подгруппам в теории групп.

Подмножество $I$ кольца $R$ называют **левым идеалом**, если выполняется:

1. $\forall a, b \in I:  \ \ \ a-b \in I$ -- подгруппа по сложению (критерий подгруппы)

2. $\forall a \in I: \forall r \in R\ \ \ ra \in I$ -- свойство втягивания

Домножение на $r$ происходит слева. 

Аналогично левому идеалу определяется *правый идеал*.

Идеал, являющийся и левым и правым, называют **двусторонним идеалом**.

## Примеры

- $\{0\}$ в произвольном кольце

- $m\mathbb{Z} = \{mr\ |\ r\in \mathbb{Z}\},\  m \in \mathbb{N}$ -- двусторонний идеал целых чисел делящихся на натуральное $m$.

## Главный идеал

Пусть $R$ -- коммутативное кольцо. **Главным идеалом, порожденным элементом а**, называют идеал вида:

$$
(a) = \{ra + na\ \ |\ r\in R, \ n\in \mathbb{Z}\}
$$

умножение на $r$ и $n$ раз операция над $a$.

Если $R$ -- кольцо с единицей, то главный идеал можно записать в следующем виде:

$$
(a) = \{ra \ | \ r\in R\}
$$


## Кольца главных идеалов

Кольца $R$, в которых все идеалы $I \ne R$ являются главными, называются **кольцами главных идеалов**.

## Примеры 

- Кольцо $\mathbf{Z}_m$ является кольцом главных идеалов
 
- Кольцо $\mathbf{R}[x]$ является кольцом главных идеалов

